2019-12-16 14:18:25 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:36)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 14:18:33 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:36)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 14:20:15 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:36)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 14:23:14 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "project0.users" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:36)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 14:24:14 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name emp_id was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:43)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 14:26:28 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name supervisor was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:53)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 14:27:49 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name supervisor was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:53)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 14:59:43 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name supervisor was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:53)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 15:07:25 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name supervisor was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:53)
	at com.revature.Driver.main(Driver.java:71)
2019-12-16 18:48:47 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name supervisor was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:53)
	at com.revature.Driver.main(Driver.java:72)
2019-12-16 19:39:18 WARN  EmployeeDAOImpl:61 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name supervisor was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:53)
	at com.revature.Driver.main(Driver.java:72)
2019-12-16 20:38:11 WARN  EmployeeDAOImpl:63 - Unable to retrieve all users 'employees' 
org.postgresql.util.PSQLException: The column name emp_type was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:47)
	at com.revature.Driver.main(Driver.java:18)
2019-12-16 20:38:43 WARN  EmployeeDAOImpl:63 - Unable to retrieve all users 'employees' 
org.postgresql.util.PSQLException: The column name emp_type was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:47)
	at com.revature.Driver.main(Driver.java:18)
2019-12-16 20:58:50 WARN  EmployeeDAOImpl:63 - Unable to retrieve all users 'employees' 
org.postgresql.util.PSQLException: The column name emp_type was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:47)
	at com.revature.Driver.main(Driver.java:18)
2019-12-17 20:45:52 WARN  EmployeesAdminDAOImpl:41 - Unable to verify if employee exists
org.postgresql.util.PSQLException: ERROR: relation "project0.employeesadmins" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.EmployeesAdminDAOImpl.employeeExists(EmployeesAdminDAOImpl.java:29)
	at com.revature.services.EmployeeAdminLogic.existingEmployeeCheck(EmployeeAdminLogic.java:199)
	at com.revature.services.EmployeeAdminLogic.existingUserLoginEmployee(EmployeeAdminLogic.java:38)
	at com.revature.services.Bank.startHere(Bank.java:64)
	at com.revature.Driver.main(Driver.java:10)
2019-12-17 22:43:50 WARN  CustomersDAOImpl:123 - 
org.postgresql.util.PSQLException: No value specified for parameter 5.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:120)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:83)
	at com.revature.Driver.main(Driver.java:10)
2019-12-17 23:26:35 WARN  CustomersDAOImpl:123 - ///
org.postgresql.util.PSQLException: No value specified for parameter 5.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:120)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-17 23:36:14 WARN  CustomersDAOImpl:123 - ///
org.postgresql.util.PSQLException: No value specified for parameter 5.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:120)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-17 23:51:22 WARN  CustomersDAOImpl:123 - ///
org.postgresql.util.PSQLException: No value specified for parameter 5.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:120)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-17 23:56:20 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: No value specified for parameter 5.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:122)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-17 23:57:14 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: The column index is out of range: 6, number of columns: 5.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setLiteralParameter(SimpleParameterList.java:123)
	at org.postgresql.jdbc.PgPreparedStatement.bindLiteral(PgPreparedStatement.java:1001)
	at org.postgresql.jdbc.PgPreparedStatement.setBoolean(PgPreparedStatement.java:267)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:120)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-17 23:58:05 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: The column index is out of range: 6, number of columns: 5.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setLiteralParameter(SimpleParameterList.java:123)
	at org.postgresql.jdbc.PgPreparedStatement.bindLiteral(PgPreparedStatement.java:1001)
	at org.postgresql.jdbc.PgPreparedStatement.setBoolean(PgPreparedStatement.java:267)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:120)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-17 23:59:43 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:122)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:01:49 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:122)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:03:59 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:122)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:07:11 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:122)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:10:09 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:11:42 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:13:39 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:17:20 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:20:08 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:20:49 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:22:25 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:122)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:23:43 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:31:41 WARN  EmployeesAdminDAOImpl:41 - Can't figure out if employee exists
org.postgresql.util.PSQLException: ERROR: relation "project0.employeesadmins" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.EmployeesAdminDAOImpl.employeeExists(EmployeesAdminDAOImpl.java:29)
	at com.revature.services.EmployeeAdminLogic.existingEmployeeCheck(EmployeeAdminLogic.java:199)
	at com.revature.services.EmployeeAdminLogic.existingUserLoginEmployee(EmployeeAdminLogic.java:38)
	at com.revature.services.Bank.startHere(Bank.java:63)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:38:28 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:39:52 WARN  EmployeesAdminDAOImpl:41 - Can't figure out if employee exists
org.postgresql.util.PSQLException: ERROR: relation "project0.employeesadmins" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.EmployeesAdminDAOImpl.employeeExists(EmployeesAdminDAOImpl.java:29)
	at com.revature.services.EmployeeAdminLogic.existingEmployeeCheck(EmployeeAdminLogic.java:199)
	at com.revature.services.EmployeeAdminLogic.existingUserLoginEmployee(EmployeeAdminLogic.java:38)
	at com.revature.services.Bank.startHere(Bank.java:71)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 00:40:37 WARN  EmployeesAdminDAOImpl:41 - Can't figure out if employee exists
org.postgresql.util.PSQLException: ERROR: relation "project0.employeesadmins" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.EmployeesAdminDAOImpl.employeeExists(EmployeesAdminDAOImpl.java:29)
	at com.revature.services.EmployeeAdminLogic.existingEmployeeCheck(EmployeeAdminLogic.java:199)
	at com.revature.services.EmployeeAdminLogic.existingUserLoginEmployee(EmployeeAdminLogic.java:38)
	at com.revature.services.Bank.startHere(Bank.java:71)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:08:35 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:122)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:35:26 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:116)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:43:14 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:116)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:44:48 WARN  CustomersDAOImpl:125 - ///
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:116)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:50:14 WARN  CustomersDAOImpl:126 - ///
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:116)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:52:18 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:53:24 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:59:24 WARN  CustomersDAOImpl:126 - ///
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:116)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 05:59:43 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:49)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 06:08:53 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 06:11:39 WARN  CustomersDAOImpl:126 - ///
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:116)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 06:36:20 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 06:48:47 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 06:52:33 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 06:59:55 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:02:41 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:03:38 WARN  CustomersDAOImpl:98 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:86)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:08:39 WARN  CustomersDAOImpl:99 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:87)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:17:04 WARN  CustomersDAOImpl:101 - Can't find out if user exists or not
org.postgresql.util.PSQLException: Unterminated string literal started at position 41 in SQL SELECT * FROM customers WHERE username = 'username123;. Expected  char
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1303)
	at org.postgresql.core.Parser.parseSql(Parser.java:1210)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:1154)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:327)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:89)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:17:50 WARN  CustomersDAOImpl:101 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:89)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:18:22 WARN  CustomersDAOImpl:101 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:89)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:19:35 WARN  CustomersDAOImpl:101 - Can't find out if user exists or not
org.postgresql.util.PSQLException: ERROR: relation "customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at com.revature.repositories.CustomersDAOImpl.customerExists(CustomersDAOImpl.java:89)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:91)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:23:00 WARN  CustomersDAOImpl:44 - Unable to get Customer from database
org.postgresql.util.PSQLException: ERROR: relation "project0.customers" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.CustomersDAOImpl.getCustomerByUserName(CustomersDAOImpl.java:30)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:92)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:25:38 WARN  AccountsDAOImpl:76 - Can't get user's accounts
org.postgresql.util.PSQLException: ERROR: relation "project0.bankaccounts" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.AccountsDAOImpl.getAccountFromUser(AccountsDAOImpl.java:59)
	at com.revature.services.CustomerLogic.grabWholeCustomer(CustomerLogic.java:26)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:95)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:34:59 WARN  AccountsDAOImpl:76 - Can't get user's accounts
org.postgresql.util.PSQLException: ERROR: relation "project0.bankaccounts" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.AccountsDAOImpl.getAccountFromUser(AccountsDAOImpl.java:59)
	at com.revature.services.CustomerLogic.grabWholeCustomer(CustomerLogic.java:26)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:95)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 07:37:29 WARN  CustomersDAOImpl:128 - ///
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.createCustomer(CustomersDAOImpl.java:118)
	at com.revature.services.CustomerLogic.setNewUserFields(CustomerLogic.java:81)
	at com.revature.services.Bank.startHere(Bank.java:90)
	at com.revature.Driver.main(Driver.java:13)
2019-12-18 12:42:48 WARN  AccountsDAOImpl:76 - Can't get user's accounts
org.postgresql.util.PSQLException: The column name username was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.AccountsDAOImpl.getAccountFromUser(AccountsDAOImpl.java:64)
	at com.revature.services.CustomerLogic.grabWholeCustomer(CustomerLogic.java:26)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:95)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:15)
2019-12-18 12:44:08 WARN  AccountsDAOImpl:76 - Can't get user's accounts
org.postgresql.util.PSQLException: The column name username was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2480)
	at com.revature.repositories.AccountsDAOImpl.getAccountFromUser(AccountsDAOImpl.java:64)
	at com.revature.services.CustomerLogic.grabWholeCustomer(CustomerLogic.java:26)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:95)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:15)
2019-12-18 12:45:06 WARN  TransactionsDAOImpl:69 - Couldn't get recent transactions
org.postgresql.util.PSQLException: ERROR: function recenttransactions(integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.TransactionsDAOImpl.getTransactions(TransactionsDAOImpl.java:52)
	at com.revature.services.CustomerLogic.grabWholeCustomer(CustomerLogic.java:29)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:95)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:15)
2019-12-18 12:45:06 WARN  TransactionsDAOImpl:69 - Couldn't get recent transactions
org.postgresql.util.PSQLException: ERROR: function recenttransactions(integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.TransactionsDAOImpl.getTransactions(TransactionsDAOImpl.java:52)
	at com.revature.services.CustomerLogic.grabWholeCustomer(CustomerLogic.java:29)
	at com.revature.services.CustomerLogic.existingCustomerCheck(CustomerLogic.java:95)
	at com.revature.services.CustomerLogic.existingUserLoginCustomer(CustomerLogic.java:48)
	at com.revature.services.Bank.startHere(Bank.java:54)
	at com.revature.Driver.main(Driver.java:15)
2019-12-18 15:56:55 WARN  CustomersDAOImpl:69 - Can't get user information
org.postgresql.util.PSQLException: The column index is out of range: 7, number of columns: 6.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.updateCustomer(CustomersDAOImpl.java:65)
	at com.revature.services.EmployeeAdminLogic.setApproval(EmployeeAdminLogic.java:225)
	at com.revature.services.EmployeeAdminLogic.setCustomerApproval(EmployeeAdminLogic.java:118)
	at com.revature.services.EmployeeAdminLogic.existingEmployeeMainMenu(EmployeeAdminLogic.java:69)
	at com.revature.services.Bank.startHere(Bank.java:65)
	at com.revature.Driver.main(Driver.java:15)
2019-12-18 15:59:51 WARN  CustomersDAOImpl:69 - Can't get user information
org.postgresql.util.PSQLException: The column index is out of range: 7, number of columns: 6.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:64)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:127)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1018)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:348)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:335)
	at com.revature.repositories.CustomersDAOImpl.updateCustomer(CustomersDAOImpl.java:65)
	at com.revature.services.EmployeeAdminLogic.setApproval(EmployeeAdminLogic.java:220)
	at com.revature.services.EmployeeAdminLogic.setCustomerApproval(EmployeeAdminLogic.java:118)
	at com.revature.services.EmployeeAdminLogic.existingEmployeeMainMenu(EmployeeAdminLogic.java:69)
	at com.revature.services.Bank.startHere(Bank.java:65)
	at com.revature.Driver.main(Driver.java:15)
